services:
  app:
    image: ${IMAGE}
    pull_policy: "missing"
    depends_on:
      db:
        condition: "service_started"
      redis:
        condition: "service_started"
    init: true
    ports:
      - "9999:3000"
    volumes:
      - type: bind
        source: "./"
        target: "/root/work"
        consistency: "consistent"
    entrypoint: /root/show-help-in-app-container-then-wait.sh
    working_dir: /root/work
  db:
    image: postgres:15
    pull_policy: "missing"
    environment:
      POSTGRES_PASSWORD: postgres
  redis:
    image: redis:6
    pull_policy: "missing"
# vim: ft=yaml nospell
